<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
        <ProjectReference Include="../../src/AterraEngine.Core.DependencyInjection/AterraEngine.Core.DependencyInjection.csproj"/>
        <ProjectReference Include="../../src/AterraEngine.Core.DependencyInjection.Generators/AterraEngine.Core.DependencyInjection.Generators.csproj"/>
    </ItemGroup>
</Project>
