// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace AterraEngine.Core.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator(LanguageNames.CSharp)]
public sealed class ActivatorGenerator : IIncrementalGenerator {
    internal const string AttributeName = "AterraEngine.Core.DependencyInjection.GenerateServiceActivatorsAttribute";

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Symbols and syntax never leave the transform. ValueTuple<string,...> provides structural
        // equality, so unrelated edits can reuse the output without rooting old compilations.
        IncrementalValuesProvider<(string Hint, string Source, string Error)> models = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (context, token) => Describe(
                (INamedTypeSymbol)context.TargetSymbol,
                context.Attributes[0],
                context.SemanticModel.Compilation, token)
        ).WithTrackingName("ActivatorModels");
        
        context.RegisterSourceOutput(models, action: static (output, model) => {
            if (model.Error.Length == 0) output.AddSource(model.Hint, SourceText.From(model.Source, Encoding.UTF8));
        });
    }

    internal static (string Hint, string Source, string Error) Describe(
        INamedTypeSymbol module,
        AttributeData attribute,
        Compilation compilation,
        CancellationToken token
    ) {
        if (!module.IsStatic || module.Arity != 0 || module.ContainingType is not null || module.IsFileLocal ||
            module.DeclaringSyntaxReferences.Any(reference => reference.GetSyntax(token) is not ClassDeclarationSyntax declaration ||
                !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
            return ("", "", "The activator module must be a top-level, non-generic static partial class.");
        
        if (module.GetMembers("AddActivators").Any(member => !member.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == "System.CodeDom.Compiler.GeneratedCodeAttribute")))
            return ("", "", "AddActivators is reserved for generated code.");

        string ns = module.ContainingNamespace.IsGlobalNamespace ? "" : module.ContainingNamespace.ToDisplayString();
        var text = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        if (ns.Length != 0) text.Append("namespace ").Append(ns).AppendLine(";");
        text.Append("static partial class @").Append(module.Name).AppendLine(" {");
        text.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"Aterra.DependencyInjection\", \"1.0\")]");
        text.AppendLine("    public static void AddActivators(global::AterraEngine.Core.DependencyInjection.Collection.ServiceCollection services) {");
        
        var seen = new HashSet<string>(StringComparer.Ordinal);
        if (attribute.ConstructorArguments.Length != 1 || attribute.ConstructorArguments[0].IsNull)
            return ("", "", "Supply a list of concrete implementation types.");

        foreach (TypedConstant argument in attribute.ConstructorArguments[0].Values) {
            token.ThrowIfCancellationRequested();
            if (argument.Value is not INamedTypeSymbol type || type.TypeKind != TypeKind.Class || type.IsAbstract ||
                type.IsStatic || type.IsFileLocal || type.IsUnboundGenericType || !compilation.IsSymbolAccessibleWithin(type, module))
                return ("", "", $"Implementation '{argument.Value}' must be a closed, accessible, concrete class.");

            string name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!seen.Add(name)) return ("", "", $"Implementation '{name}' is listed more than once.");

            IMethodSymbol[] constructors = type.InstanceConstructors.Where(c => c.DeclaredAccessibility == Accessibility.Public).ToArray();
            if (constructors.Length != 1) return ("", "", $"Implementation '{name}' must have exactly one public constructor.");

            IMethodSymbol constructor = constructors[0];
            if (constructor.Parameters.Any(p => p.RefKind != RefKind.None || p.Type.IsRefLikeType || p.Type.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer or TypeKind.Dynamic))
                return ("", "", $"Constructor for '{name}' has unsupported ref, pointer, dynamic or ref-like parameters.");

            bool required = false;
            for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType) {
                required |= current.GetMembers().Any(member => member is IPropertySymbol { IsRequired: true } or IFieldSymbol { IsRequired: true });
            }

            if (required && !constructor.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute"))
                return ("", "", $"Constructor for '{name}' must set required members (SetsRequiredMembers).");

            string[] dependencies = constructor.Parameters.Select(p => p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToArray();
            text.Append("        services.AddGeneratedActivator<").Append(name).Append(">(static (ref global::AterraEngine.Core.DependencyInjection.GeneratedServiceResolver resolver) => new ").Append(name).Append('(')
                .Append(string.Join(", ", dependencies.Select(dependency => $"resolver.Get<{dependency}>()"))).Append(')');
            foreach (string dependency in dependencies) text.Append(", typeof(").Append(dependency).Append(')');
            text.AppendLine(");");
        }

        text.AppendLine("    }").AppendLine("}");
        // Hex-encoded full identity avoids collisions between namespace/name separator combinations.
        string hint = string.Concat(Encoding.UTF8.GetBytes(module.ToDisplayString()).Select(value => value.ToString("x2"))) + ".Activators.g.cs";
        return (hint, text.ToString(), "");
    }
}

/// <summary>Diagnostics run separately from the incremental generation pipeline, per Roslyn's cookbook.</summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ActivatorDeclarationAnalyzer : DiagnosticAnalyzer {
    private static readonly DiagnosticDescriptor InvalidDeclaration = new("ADI001", "Invalid service activator declaration",
        "{0}", "Aterra.DependencyInjection", DiagnosticSeverity.Error, true);
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [InvalidDeclaration];
    public override void Initialize(AnalysisContext context) {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSyntaxNodeAction(action: static context => {
            var syntax = (TypeDeclarationSyntax)context.Node;
            if (syntax.AttributeLists.Count == 0 || context.SemanticModel.GetDeclaredSymbol(syntax, context.CancellationToken) is not {} symbol) return;

            AttributeData? attribute = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ActivatorGenerator.AttributeName);
            if (attribute?.ApplicationSyntaxReference?.SyntaxTree != syntax.SyntaxTree ||
                !syntax.Span.Contains(attribute.ApplicationSyntaxReference.Span)) return;

            (string Hint, string Source, string Error) model = ActivatorGenerator.Describe(symbol, attribute, context.Compilation, context.CancellationToken);
            if (model.Error.Length != 0)
                context.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration,
                    attribute.ApplicationSyntaxReference.GetSyntax(context.CancellationToken).GetLocation(), model.Error));
        }, SyntaxKind.ClassDeclaration, SyntaxKind.RecordDeclaration);
    }
}
