using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace AterraEngine.Core.DependencyInjection.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ActivatorGenerator : IIncrementalGenerator {
    internal const string ServiceAttribute = "AterraEngine.Core.DependencyInjection.ServiceAttribute<TService>";
    internal const string HostAttribute = "AterraEngine.Core.DependencyInjection.HostServiceAttribute<TService>";
    internal const string SingletonAttribute = "AterraEngine.Core.DependencyInjection.SingletonServiceAttribute<TService>";
    internal const string TransientAttribute = "AterraEngine.Core.DependencyInjection.TransientServiceAttribute<TService>";
    internal const string WorldAttribute = "AterraEngine.Core.DependencyInjection.WorldServiceAttribute<TService>";
    internal const string SceneAttribute = "AterraEngine.Core.DependencyInjection.SceneServiceAttribute<TService>";
    internal const string ScopedAttribute = "AterraEngine.Core.DependencyInjection.ScopedServiceAttribute<TService, TScope>";
    internal const string ConstructorAttribute = "AterraEngine.Core.DependencyInjection.ServiceConstructorAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace AterraEngine.Core.DependencyInjection;

        internal enum ServiceLifetime {
            Transient,
            Singleton,
            Host,
            World,
            Scene
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class ServiceAttribute<TService>(ServiceLifetime lifetime) : global::System.Attribute {
            public ServiceLifetime Lifetime { get; } = lifetime;
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class HostServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class SingletonServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class TransientServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class WorldServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class SceneServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class ScopedServiceAttribute<TService, TScope> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Constructor, Inherited = false)]
        internal sealed class ServiceConstructorAttribute : global::System.Attribute;
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("Aterra.ServiceAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<(string Key, string Body, string Error)> models = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
            transform: static (syntaxContext, token) => DescribeDeclaration(syntaxContext, token)
        ).Where(static model => !string.IsNullOrEmpty(model.Key)).WithTrackingName("ServiceModels");

        context.RegisterSourceOutput(models.Collect(), action: static (output, collected) => {
            string[] bodies = collected.Where(model => model.Error.Length == 0)
                .OrderBy(model => model.Key, StringComparer.Ordinal).Select(model => model.Body).ToArray();
            if (bodies.Length == 0) return;

            var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
            source.AppendLine("internal static class __AterraGeneratedServiceRegistration {");
            source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            source.AppendLine("    internal static void Initialize() => global::AterraEngine.Core.DependencyInjection.GeneratedServiceRegistration.RegisterAssembly(typeof(__AterraGeneratedServiceRegistration).Assembly, Register);");
            source.AppendLine("    private static void Register(global::AterraEngine.Core.DependencyInjection.Collection.ServiceCollection services) {");
            foreach (string body in bodies) source.Append(body);
            source.AppendLine("    }").AppendLine("}");
            output.AddSource("Aterra.GeneratedServiceRegistration.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static (string Key, string Body, string Error) DescribeDeclaration(GeneratorSyntaxContext context, CancellationToken token) {
        var declaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration, token) is not { } type) return default;

        ImmutableArray<AttributeData> attributes = type.GetAttributes().Where(IsServiceAttribute).ToImmutableArray();
        SyntaxReference? firstReference = attributes.IsEmpty ? null : attributes[0].ApplicationSyntaxReference;
        if (firstReference is null || firstReference.SyntaxTree != declaration.SyntaxTree ||
            !declaration.Span.Contains(firstReference.Span)) return default;
        return Describe(type, attributes, context.SemanticModel.Compilation, token);
    }

    internal static (string Key, string Body, string Error) Describe(
        INamedTypeSymbol type,
        ImmutableArray<AttributeData> attributes,
        Compilation compilation,
        CancellationToken token
    ) {
        string key = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsStatic || type.IsFileLocal || type.TypeParameters.Length != 0 ||
            !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly))
            return (key, "", $"Implementation '{key}' must be an accessible, non-generic concrete class.");

        IMethodSymbol[] marked = type.InstanceConstructors.Where(HasConstructorAttribute).ToArray();
        if (marked.Length > 1) return (key, "", $"Implementation '{key}' has more than one constructor marked [ServiceConstructor].");

        IMethodSymbol[] constructors = type.InstanceConstructors.Where(constructor => constructor.DeclaredAccessibility == Accessibility.Public).ToArray();
        IMethodSymbol? selected = marked.SingleOrDefault();
        if (selected is not null && selected.DeclaredAccessibility != Accessibility.Public)
            return (key, "", $"The [ServiceConstructor] constructor for '{key}' must be public.");
        if (constructors.Length == 0)
            return (key, "", $"Implementation '{key}' must have a public constructor.");
        if (constructors.Length > 1 && selected is null)
            return (key, "", $"Implementation '{key}' has multiple public constructors; mark exactly one with [ServiceConstructor].");
        selected ??= constructors[0];

        if (selected.Parameters.Any(parameter => parameter.RefKind != RefKind.None || parameter.Type.IsRefLikeType ||
            parameter.Type.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer or TypeKind.Dynamic))
            return (key, "", $"Constructor for '{key}' has unsupported ref, pointer, dynamic or ref-like parameters.");

        bool required = false;
        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
            required |= current.GetMembers().Any(member => member is IPropertySymbol { IsRequired: true } or IFieldSymbol { IsRequired: true });
        if (required && !selected.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() ==
                "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute"))
            return (key, "", $"Constructor for '{key}' must set required members (SetsRequiredMembers).");

        string[] dependencies = selected.Parameters.Select(parameter =>
            parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToArray();
        var body = new StringBuilder();
        body.Append("        services.AddGeneratedActivator<").Append(key)
            .Append(">(static (ref global::AterraEngine.Core.DependencyInjection.GeneratedServiceResolver resolver) => new ")
            .Append(key).Append('(').Append(string.Join(", ", dependencies.Select(dependency => $"resolver.Get<{dependency}>()"))).Append(')');
        foreach (string dependency in dependencies) body.Append(", typeof(").Append(dependency).Append(')');
        body.AppendLine(");");

        var seenServices = new HashSet<string>(StringComparer.Ordinal);
        foreach (AttributeData attribute in attributes) {
            token.ThrowIfCancellationRequested();
            if (attribute.AttributeClass?.TypeArguments.FirstOrDefault() is not INamedTypeSymbol service) continue;
            string serviceName = service.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!seenServices.Add(serviceName))
                return (key, "", $"Implementation '{key}' registers service '{serviceName}' more than once.");
            var conversion = compilation.ClassifyCommonConversion(type, service);
            if (!SymbolEqualityComparer.Default.Equals(type, service) &&
                (!conversion.Exists || !conversion.IsImplicit || !conversion.IsReference))
                return (key, "", $"Implementation '{key}' is not assignable to service '{serviceName}'.");

            string attributeName = attribute.AttributeClass.OriginalDefinition.ToDisplayString();
            string lifetime;
            if (attributeName == HostAttribute) lifetime = "global::AterraEngine.Core.DependencyInjection.Lifetime.Host";
            else if (attributeName == SingletonAttribute) lifetime = "global::AterraEngine.Core.DependencyInjection.Lifetime.Singleton";
            else if (attributeName == TransientAttribute) lifetime = "global::AterraEngine.Core.DependencyInjection.Lifetime.Transient";
            else if (attributeName == WorldAttribute) lifetime = "global::AterraEngine.Core.DependencyInjection.Lifetime.Of<global::AterraEngine.Core.DependencyInjection.Scopes.World>()";
            else if (attributeName == SceneAttribute) lifetime = "global::AterraEngine.Core.DependencyInjection.Lifetime.Of<global::AterraEngine.Core.DependencyInjection.Scopes.Scene>()";
            else if (attributeName == ScopedAttribute) {
                string scope = attribute.AttributeClass.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                lifetime = $"global::AterraEngine.Core.DependencyInjection.Lifetime.Of<{scope}>()";
            }
            else if (attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is int value) {
                lifetime = value switch {
                    0 => "global::AterraEngine.Core.DependencyInjection.Lifetime.Transient",
                    1 => "global::AterraEngine.Core.DependencyInjection.Lifetime.Singleton",
                    2 => "global::AterraEngine.Core.DependencyInjection.Lifetime.Host",
                    3 => "global::AterraEngine.Core.DependencyInjection.Lifetime.Of<global::AterraEngine.Core.DependencyInjection.Scopes.World>()",
                    4 => "global::AterraEngine.Core.DependencyInjection.Lifetime.Of<global::AterraEngine.Core.DependencyInjection.Scopes.Scene>()",
                    _ => ""
                };
                if (lifetime.Length == 0) return (key, "", $"Implementation '{key}' has an invalid ServiceLifetime value.");
            }
            else return (key, "", $"Implementation '{key}' has an invalid service attribute.");

            body.Append("        services.Add<").Append(serviceName).Append(", ").Append(key).Append(">(").Append(lifetime).AppendLine(");");
        }

        return (key, body.ToString(), "");
    }

    internal static bool IsServiceAttribute(AttributeData attribute) {
        string? name = attribute.AttributeClass?.OriginalDefinition.ToDisplayString();
        return name is ServiceAttribute or HostAttribute or SingletonAttribute or TransientAttribute or WorldAttribute or SceneAttribute or ScopedAttribute;
    }

    private static bool HasConstructorAttribute(IMethodSymbol constructor)
        => constructor.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == ConstructorAttribute);
}

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ActivatorDeclarationAnalyzer : DiagnosticAnalyzer {
    private static readonly DiagnosticDescriptor InvalidDeclaration = new("ADI001", "Invalid service activator declaration",
        "{0}", "Aterra.DependencyInjection", DiagnosticSeverity.Error, true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [InvalidDeclaration];

    public override void Initialize(AnalysisContext context) {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSyntaxNodeAction(Analyze, SyntaxKind.ClassDeclaration, SyntaxKind.RecordDeclaration);
    }

    private static void Analyze(SyntaxNodeAnalysisContext context) {
        var declaration = (TypeDeclarationSyntax)context.Node;
        if (declaration.AttributeLists.Count == 0 || context.SemanticModel.GetDeclaredSymbol(declaration, context.CancellationToken) is not { } type)
            return;

        ImmutableArray<AttributeData> attributes = type.GetAttributes().Where(ActivatorGenerator.IsServiceAttribute).ToImmutableArray();
        SyntaxReference? firstReference = attributes.IsEmpty ? null : attributes[0].ApplicationSyntaxReference;
        if (firstReference is null || firstReference.SyntaxTree != declaration.SyntaxTree ||
            !declaration.Span.Contains(firstReference.Span)) return;

        (string _, string _, string error) = ActivatorGenerator.Describe(type, attributes, context.Compilation, context.CancellationToken);
        if (error.Length != 0)
            context.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration,
                attributes[0].ApplicationSyntaxReference!.GetSyntax(context.CancellationToken).GetLocation(), error));
    }
}
