// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AterraEngine.Core.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
internal static class ServiceRegistrationEmitter {
    internal static string Render(ImmutableArray<(string Key, string Body, string Error)> collected, CancellationToken token) {
        string[] bodies = collected.Where(model => model.Error.Length == 0)
            .OrderBy(keySelector: model => model.Key, StringComparer.Ordinal).Select(model => model.Body).ToArray();
        if (bodies.Length == 0) return "";

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        source.AppendLine("internal static class __AterraGeneratedServiceRegistration {");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Initialize() => global::AterraEngine.Core.DependencyInjection.GeneratedServiceRegistration.RegisterAssembly(typeof(__AterraGeneratedServiceRegistration).Assembly, Register);");
        source.AppendLine("    private static void Register(global::AterraEngine.Core.DependencyInjection.Collection.ServiceCollection services) {");
        foreach (string body in bodies) {
            token.ThrowIfCancellationRequested();
            source.Append(body);
        }

        source.AppendLine("    }").AppendLine("}");
        return source.ToString();
    }

    internal static void Emit(SourceProductionContext output, string source) {
        if (source.Length != 0)
            output.AddSource("Aterra.GeneratedServiceRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
