// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
namespace AterraEngine.Core.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
internal static class ServiceAttributeSource {
    // These declarations form the source-level opt-in contract. Conservative syntax keeps the generated contract
    // usable by C# 11 consumers, while Embedded marks prevent duplicate internal definitions from leaking warnings
    // through InternalsVisibleTo relationships.
    internal const string Text = """
        // <auto-generated/>
        #nullable enable
        namespace AterraEngine.Core.DependencyInjection;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class ServiceAttribute<TService> : global::System.Attribute {
            public ServiceAttribute(global::AterraEngine.Core.DependencyInjection.ServiceScope scope) {
                Scope = scope;
            }

            public global::AterraEngine.Core.DependencyInjection.ServiceScope Scope { get; private set; }
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class HostServiceAttribute<TService> : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class SingletonServiceAttribute<TService> : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class TransientServiceAttribute<TService> : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class WorldServiceAttribute<TService> : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class SceneServiceAttribute<TService> : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class ScopedServiceAttribute<TService, TScope> : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class GeneratedServiceClosureAttribute<TService, TImplementation> : global::System.Attribute {
            public GeneratedServiceClosureAttribute(global::AterraEngine.Core.DependencyInjection.ServiceScope scope) {
                Scope = scope;
            }

            public global::AterraEngine.Core.DependencyInjection.ServiceScope Scope { get; }
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Constructor, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class ServiceConstructorAttribute : global::System.Attribute { }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class KeyedDependencyAttribute<TService, TKey> : global::System.Attribute {
            public KeyedDependencyAttribute(TKey key) { Key = key; }
            public TKey Key { get; }
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
        [global::Microsoft.CodeAnalysis.Embedded]
        public sealed class DecoratedDependencyAttribute<TService> : global::System.Attribute { }
        """;
}
