// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
namespace AterraEngine.Core.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
internal static class ServiceAttributeSource {
    internal const string Text = """
        // <auto-generated/>
        #nullable enable
        namespace AterraEngine.Core.DependencyInjection;

        internal enum ServiceLifetime {
            Transient,
            Singleton,
            Host,
            World,
            Scene
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class ServiceAttribute<TService>(ServiceLifetime lifetime) : global::System.Attribute {
            public ServiceLifetime Lifetime { get; } = lifetime;
        }

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class HostServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class SingletonServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class TransientServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class WorldServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class SceneServiceAttribute<TService> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class ScopedServiceAttribute<TService, TScope> : global::System.Attribute;

        [global::System.AttributeUsage(global::System.AttributeTargets.Constructor, Inherited = false)]
        internal sealed class ServiceConstructorAttribute : global::System.Attribute;
        """;
}
