// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AterraEngine.Core.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
internal static class ServiceRegistrationEmitter {
    internal static string Render(ImmutableArray<(string Key, string Body, string Error)> collected, CancellationToken token) {
        // Invalid models are owned by ActivatorDeclarationAnalyzer and must not contribute uncompilable registrations.
        // Sorting by implementation identity makes output independent of syntax-tree and provider traversal order.
        string[] bodies = collected.Where(model => model.Error.Length == 0)
            .OrderBy(keySelector: model => model.Key, StringComparer.Ordinal).Select(model => model.Body).ToArray();
        if (bodies.Length == 0) return "";

        // One module initializer records a registration callback for this assembly. ServiceCollection applies that
        // callback later, so scanning or reflection is unnecessary at runtime and remains Native AOT friendly.
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        source.AppendLine("internal static class __AterraGeneratedServiceRegistration {");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Initialize() => global::AterraEngine.Core.DependencyInjection.GeneratedServiceRegistration.RegisterAssembly(typeof(__AterraGeneratedServiceRegistration).Assembly, Register);");
        source.AppendLine("    private static void Register(global::AterraEngine.Core.DependencyInjection.ServiceCollection services) {");
        var registeredServices = new HashSet<string>(StringComparer.Ordinal);
        foreach (string body in bodies) {
            token.ThrowIfCancellationRequested();
            foreach (string line in body.Split('\n')) {
                const string prefix = "        services.Add<";
                if (!line.StartsWith(prefix, StringComparison.Ordinal)) {
                    source.AppendLine(line);
                    continue;
                }

                int comma = line.IndexOf(", ", prefix.Length, StringComparison.Ordinal);
                if (comma < 0) {
                    source.AppendLine(line);
                    continue;
                }

                string service = line.Substring(prefix.Length, comma - prefix.Length);
                source.Append("        services.").Append(registeredServices.Add(service) ? "Add<" : "AddEnumerable<")
                    .Append(line.Substring(prefix.Length)).AppendLine();
            }
        }

        source.AppendLine("    }").AppendLine("}");
        return source.ToString();
    }

    internal static void Emit(SourceProductionContext output, string source) {
        // An assembly with no valid service declarations needs no registrar or module initializer.
        if (source.Length != 0)
            output.AddSource("Aterra.GeneratedServiceRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
