<?xml version='1.0' encoding='utf-8'?>
<Project>
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>15.0</LangVersion>

        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ExcludeByFile>**/*.g.cs;**/*.g.props;**/*.g.targets;**/obj/**;**/bin/**</ExcludeByFile>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AterraEngine.Core.DependencyInjection"/>
        <InternalsVisibleTo Include="AterraEngine.Core.DependencyInjection.Generators"/>
        <InternalsVisibleTo Include="AterraEngine.Core.Shared"/>
        <InternalsVisibleTo Include="AterraEngine.Core"/>

        <InternalsVisibleTo Include="AterraEngine.Core.DependencyInjection.Generators.Tests"/>
        <InternalsVisibleTo Include="AterraEngine.Core.DependencyInjection.Tests"/>
    </ItemGroup>
</Project>
