<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <PublishAot>true</PublishAot>
        <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
        <TrimmerSingleWarn>false</TrimmerSingleWarn>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../AterraEngine.Core.DependencyInjection/AterraEngine.Core.DependencyInjection.csproj"/>
        <ProjectReference Include="../AterraEngine.Core.DependencyInjection.Generators/AterraEngine.Core.DependencyInjection.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>
</Project>
